### ISSUE TITLE
Missing /var/log/clusterhc directory

### ISSUE THREAD

**Issue by DevSidious** [leoleovich/clusterhc#3]
Great job. However, there is one minor issue that can be easily fixed in code or by updating the "Installation" documentation:

[root@8569ff github.com]# /opt/go/bin/clusterhc
**open /var/log/clusterhc/clusterhc.log: no such file or directory**

[root@8569ff ~]# mkdir -v /var/log/clusterhc
mkdir: created directory ‘/var/log/clusterhc’

[root@8569ff ~]# /opt/go/bin/clusterhc

OK

**Comment by leoleovich** [comment]
Hello @DevSidious!
Thanks, fixed with https://github.com/leoleovich/clusterhc/commit/2a4dab794afa89f1c6f16f4dca01f1dfb1276734
